### ISSUE TITLE
Modifying service token is not allowed when redeploying

### ISSUE THREAD

**Issue by mbonig** [robertd/cdk-karpenter#27]
I recently tried updating a cluster with and I'm running into this error when updating Karpenter:

```
KarpenterHelmChart1D98E7F5: Modifying service token is not allowed.
```

The underlying lambda is changing. I tried just changing the ID of the construct:

```
 const karpenter = new Karpenter(this, 'KarpenterV2', {
    vpc: this.props.vpc,
    cluster: this.cluster,
  });
```

But this also fails a deploy because the Role being created is fairly static (KarpenterNodeInstanceProfile-<myClusterName>) and a second instance can't be deployed for the same cluster (So then it's a race, I can't create the new one before deleting the old one).

I wouldn't mind deleting the the old one first and staging the deploy, but this might cause an outage I'd like to avoid.

Any ideas how this can be resolved?

**Comment by robertd** [comment]
Thanks for opening the GH issue. I'm probably going to drop static instance profile naming as I experienced some issues with its length recently.

**Comment by robertd** [comment]
@mbonig Arghh... I don't think I can remove [`instanceProfileName`](https://github.com/robertd/cdk-karpenter/blob/491c8b8799b8b768898bd4884b190e57f2343d70/src/karpenter.ts#L337) because I'm using `CfnInstanceProfile` (L1) and if no name is provided then I cannot reference `this.instanceProfile.instanceProfileName` in the [provisioner section](https://github.com/robertd/cdk-karpenter/blob/491c8b8799b8b768898bd4884b190e57f2343d70/src/karpenter.ts#L435) as it's an empty string now. I don't recall seeing an L2 construct for InstanceProfile in CDK. Perhaps there should be one for this exact reason. WDYT?

**Comment by robertd** [comment]
@mbonig Give `1.7.1` a try when you get a chance.

**Comment by robertd** [comment]
@mbonig I spoke too early... pushing out `1.7.2` soon.

**Comment by robertd** [comment]
@mbonig I just updated some of our clusters with `1.7.2` and created multiple karpenter installations on the same cluster with multiple provisioners. Everything worked on my end. Let me know how it goes for you. Thanks.

Reopen this GH issue if you're still having issues.
